### ISSUE TITLE
약속 히스토리 화면 리팩토링

### ISSUE THREAD

**Issue by soulplay95** [boostcampwm-2022/android11-almost-there#155]
# TODO LIST

<img src="https://user-images.githubusercontent.com/76619688/206450690-0f468742-0807-43bc-877b-81454597bd85.png" width="30%">

- [x] 약속 시간이 빠를수록 상단에 위치하도록 약속 카드 정렬
- [x] title과 시간 사이에 `Barrier`를 걸어준다.
- [x] `Firestore`의 약속 데이터에 변경이 일어날 때 마다 즉, 자기장 갱신 주기인 1분마다 시간, HP, 순위, `Progressbar`(자기장의 상대적 위치, 내 현재 위치)가 갱신되도록 한다.
- [x] 순위 tag 동그랗게 되도록 수정
- [x] 순위 label 앞에 아이콘 넣기
- [x] HP 왼쪽에도 `Barrier` 설정
- [x] `Progressbar` 구현
- [x] [끝났어] 카드가 곧이야 탭에 있는 버그 수정

</br>

# 메모
